
# LOCALHOST
GET http://localhost:8080/

GET http://localhost:8080/contacts

GET http://localhost:8080/contacts/678af063ef767f68a1cd105c

POST http://localhost:8080/contacts

PUT http://localhost:8080/contacts/678af090ef767f68a1cd105d

DELETE http://localhost:8080/contacts/678af0adef767f68a1cd105e

# PRODUCTION 

# Get contact by ID
GET https://cse341-benjamin-main.onrender.com/contacts/678af063ef767f68a1cd105c

# Create contact
POST https://cse341-benjamin-main.onrender.com/contacts HTTP/1.1 content-type: application/json
{
"firstName":"Bruno", "lastName":"Mars", "email":"marsb@test.com", "favoriteColor":"Orange", "birthday":"06/19/1992"
}

PUT https://cse341-benjamin-main.onrender.com/contacts/678af090ef767f68a1cd105d HTTP/1.1 content-type: application/json
{
    "firstName":"Harry", "lastName":"Truman", "email":"htruman@test.com", "favoriteColor":"Maroon", "birthday":"12/12/76" 
}

### DELETE contact DELETE https://cse341-benjamin-main.onrender.com/contacts/678af0adef767f68a1cd105e HTTP/1.1 


